project:
  type: website
  output-dir: docs

website:
  title: "quiz-02"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: life-gdp.qmd
        text: Life Expectanct and GDP per Capita
      - href: life-population.qmd
        text: Life Expectancy and Population
      - href: country.qmd
        text: Country Analysis

format:
  html:
    theme:
      light: lumen
      dark: solar
    css: styles.css
    toc: true



